# Generated by Django 5.0.4 on 2024-04-24 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('host_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('host_phone', models.IntegerField(max_length=10)),
                ('host_image', models.ImageField(upload_to='images/')),
                ('host_desc', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('available', models.CharField(default='', max_length=10)),
                ('current_meeting_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=50)),
                ('visitor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('visitor_phone', models.IntegerField(max_length=10)),
                ('host', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2024, 4, 24, 12, 43, 29, 198980))),
                ('time_in', models.TimeField(default=datetime.datetime(2024, 4, 24, 12, 43, 29, 199009))),
                ('time_out', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
