# Generated by Django 5.0.4 on 2024-04-24 18:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_alter_meeting_date_alter_meeting_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='host',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 24, 18, 36, 33, 475308)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2024, 4, 24, 18, 36, 33, 475337)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='visitor_phone',
            field=models.CharField(max_length=10),
        ),
    ]
