# Generated by Django 5.0.4 on 2024-04-25 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_alter_host_host_phone_alter_host_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='address',
        ),
        migrations.RemoveField(
            model_name='host',
            name='available',
        ),
        migrations.RemoveField(
            model_name='host',
            name='current_meeting_id',
        ),
        migrations.RemoveField(
            model_name='host',
            name='host_desc',
        ),
        migrations.RemoveField(
            model_name='host',
            name='status',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 25, 6, 53, 51, 67450)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2024, 4, 25, 6, 53, 51, 67479)),
        ),
    ]
