# Generated by Django 5.0.4 on 2024-04-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0006_alter_meeting_date_alter_meeting_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='Visitor_image',
            field=models.BinaryField(),
        ),
    ]
