# Generated by Django 5.0.4 on 2024-04-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0007_alter_meeting_visitor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='Visitor_image',
        ),
        migrations.AddField(
            model_name='meeting',
            name='visitor_image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
