# Generated by Django 5.0.4 on 2024-04-26 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0008_remove_meeting_visitor_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='visitor_image_path',
        ),
        migrations.AddField(
            model_name='meeting',
            name='Visitor_image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 26, 6, 20, 57, 831017)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2024, 4, 26, 6, 20, 57, 831043)),
        ),
    ]
