# Generated by Django 5.0.4 on 2024-04-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0009_remove_meeting_visitor_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
