# Generated by Django 5.0.4 on 2024-04-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0010_alter_meeting_date_alter_meeting_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='Visitor_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
