# Generated by Django 5.0.4 on 2024-04-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0011_alter_meeting_visitor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='Visitor_image',
            new_name='visitor_image',
        ),
    ]
