# Generated by Django 5.0.4 on 2024-05-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0012_rename_visitor_image_meeting_visitor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
